* Software Freedom Day
Software Freedom Day was established in 2004. First software freedom day was observed on 28 August of 2004. About 12 teams participated in the first Software Freedom Day. Since 2006 Software Freedom Day has been held on the third Saturday of September and this year we are celebrating today, 15 September, 2018. It has grown rapidly in past few years. In 2009, 700 teams from 90 countries celebrated Software freedom day. There are hundreds of open source communities around the world who organize this event annually. Since that time it has grown in popularity and every year we have more than 300 events organized by over 100 cities from the world. Software Freedom Day this year, took place on September 15, 2018. Software freedom day was celebrated in our campus on 14 September 2018. 

*** Objectives Of Software Freedom Day 
   - To celebrate software freedom and the people behind it
   - To foster a general understanding of software freedom, and encourage adoption of free software and open standards
   - To create more equal access to opportunities through the use of participatory technologies
   - To promote constructive dialogue on responsibilities and rights in the information society
   - To be inclusive of organizations and individuals that share our Vision
   - To be pragmatic, transparent, and responsible as an organization
*** The event included:
    - Talk: The History of Free Software.
    - Live comparison: Linux vs Windows.
    - Open Discussion: Need for proper gender representation in the tech industry.
